basePath: /api/*
definitions:
  controllers.Autenticate:
    properties:
      expires_at:
        type: integer
      token:
        type: string
    type: object
  controllers.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.Category:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - description
    type: object
  models.Color:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      tone:
        type: string
      updated_at:
        type: string
    type: object
  models.Measure:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - description
    type: object
  models.Size:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - description
    type: object
  models.User:
    properties:
      created_at:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: string
      names:
        type: string
      password:
        type: string
      status:
        type: boolean
      updated_at:
        type: string
    required:
    - email
    - names
    - password
    type: object
info:
  contact: {}
  title: Redmouse API documentation.
  version: 1.0.0
paths:
  /api/categories:
    get:
      description: Get all categories, acept pagination ?page=1&page_size=10
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all categories
      tags:
      - Categories
    post:
      description: 'Create category, ej. {"description": "new category name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create category
      tags:
      - Categories
  /api/categories/{id}:
    delete:
      description: Delete category
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete category
      tags:
      - Categories
    get:
      description: Find category
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find category
      tags:
      - Categories
    put:
      description: 'Update category ej. {"description": "update category name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update category
      tags:
      - Categories
  /api/colors:
    get:
      description: Get all colors, acept pagination ?page=1&page_color=10
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all colors
      tags:
      - Colors
    post:
      description: 'Create color, ej. {"description": "new color name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create color
      tags:
      - Colors
  /api/colors/{id}:
    delete:
      description: Delete color
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete color
      tags:
      - Colors
    get:
      description: Find color
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find color
      tags:
      - Colors
    put:
      description: 'Update color ej. {"description": "update color name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Color'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update color
      tags:
      - Colors
  /api/measures:
    get:
      description: Get all measures, acept pagination ?page=1&page_size=10
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all measures
      tags:
      - Measures
    post:
      description: 'Create measure, ej. {"description": "new measure name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create measure
      tags:
      - Measures
  /api/measures/{id}:
    delete:
      description: Delete measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete measure
      tags:
      - Measures
    get:
      description: Find measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find measure
      tags:
      - Measures
    put:
      description: 'Update measure ej. {"description": "update measure name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update measure
      tags:
      - Measures
  /api/sizes:
    get:
      description: Get all sizes, acept pagination ?page=1&page_size=10
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Size'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all sizes
      tags:
      - Sizes
    post:
      description: 'Create size, ej. {"description": "new size name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Size'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create size
      tags:
      - Sizes
  /api/sizes/{id}:
    delete:
      description: Delete size
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Size'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete size
      tags:
      - Sizes
    get:
      description: Find size
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Size'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find size
      tags:
      - Sizes
    put:
      description: 'Update size ej. {"description": "update size name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Size'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update size
      tags:
      - Sizes
  /api/users:
    get:
      description: Get all users, acept pagination ?page=1&page_user=10
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all users
      tags:
      - Users
    post:
      description: 'Create user, ej. {"description": "new user name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create user
      tags:
      - Users
  /api/users/{id}:
    delete:
      description: Delete user
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete user
      tags:
      - Users
    get:
      description: Find user
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find user
      tags:
      - Users
    put:
      description: 'Update user ej. {"description": "update user name"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update user
      tags:
      - Users
  /auth/login:
    post:
      description: 'Register user, acept in json body: {"email": "jondoe@domain.com","password":
        "1234Aaaa&&d++"}'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.Autenticate'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Error'
      summary: Longin register user
      tags:
      - Auth
swagger: "2.0"
