basePath: /api/*
definitions:
  models.Measure:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      updated_at:
        type: string
    required:
    - description
    type: object
info:
  contact: {}
  title: Redmouse API documentation.
  version: 1.0.0
paths:
  /api/measures:
    get:
      description: get all measures
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all measures
      tags:
      - Measures
    post:
      description: create measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create measure
      tags:
      - Measures
  /api/measures/{id}:
    delete:
      description: delete measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete measure
      tags:
      - Measures
    get:
      description: find measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Find measure
      tags:
      - Measures
    post:
      description: update measure
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Measure'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update measure
      tags:
      - Measures
swagger: "2.0"
